### ISSUE TITLE
Change the versions of projects in the solution

### ISSUE THREAD

**Issue by dolivier-dev** [jonstodle/DotnetVersion#12]
### What should we add or change to make your life better?
I would like to change the versions of the projects in the same solution (sln).

### Why is this important to you?
For now, I would like to change the version for each project. One by one. With a simple command, I would change all the projects.

Example:
```
dotnet version --minor
mysolution found
    myprojet1 2.2.0 -> 2.3.0
    myprojet2 1.5.0 -> 1.6.0
```

**Comment by dolivier-dev** [comment]
The solution can be adding a -r option.
Recursively search the current directory

**Comment by jonstodle** [comment]
I believe this to be out of scope and better solved by existing tools available in combination with DotnetVersion. For example to get this behavior on Unix-like systems you can run the following command:

```shell
find . -name '*.csproj' | xargs -n 1 dotnet-version -- --minor -p
```
