### ISSUE TITLE
Feature Request - Support Semantic Versioning 2.0.0

### ISSUE THREAD

**Issue by xeranic** [jonstodle/DotnetVersion#2]
Semantic Version 2.0.0 is there, do we have plan to support it. Basically instead of doing 1.0.1-alpha1, we should do 1.0.1-alpha.1.

Only a dot difference :)

**Comment by jonstodle** [comment]
Thank you for this suggestion. I'm sorry I didn't get to it sooner. There's a new version propagating now which adds a fix for this.
